"""Repository seam: business logic never sees SQL."""
from __future__ import annotations

from typing import Any, Protocol

from app.models.schemas import EquipmentRecord, RunRecord


class EquipmentRepository(Protocol):
    async def get_current(self, serial_number: str, source: str) -> dict[str, Any] | None: ...

    async def get_any_source(self, serial_number: str) -> list[dict[str, Any]]: ...

    async def upsert(self, record: EquipmentRecord) -> bool:
        """Return True when a new history version was written (data actually changed)."""
        ...

    async def mark_not_found(self, serial_number: str, source: str, run_id: str) -> None: ...

    async def history(self, serial_number: str, source: str | None = None,
                      limit: int = 20) -> list[dict[str, Any]]: ...

    async def save_run(self, run: RunRecord) -> None: ...

    async def get_run(self, run_id: str) -> dict[str, Any] | None: ...

    async def find_active_run(self, idempotency_key: str) -> str | None: ...

    async def claim_idempotency(self, idempotency_key: str, run_id: str) -> bool:
        """Atomically claim the key. False means another run already owns it."""
        ...

    async def release_idempotency(self, idempotency_key: str) -> None: ...

    async def health(self) -> bool: ...
