USE SCHEMA MAYA_PROD.CORE;

-- ── Serving view: freshness computed in SQL so BI and the API agree ──────
CREATE OR REPLACE VIEW V_EQUIPMENT_CURRENT AS
SELECT e.*,
       r.LABEL                                              AS SOURCE_LABEL,
       DATEDIFF('day', e.RETRIEVED_AT, CURRENT_TIMESTAMP()) AS AGE_DAYS,
       CASE
         WHEN e.STATUS = 'NOT_FOUND'
              AND DATEDIFF('day', e.RETRIEVED_AT, CURRENT_TIMESTAMP()) <= 7 THEN 'NEGATIVE_CACHED'
         WHEN e.STATUS <> 'ACTIVE'                                          THEN 'MISSING'
         WHEN DATEDIFF('day', e.RETRIEVED_AT, CURRENT_TIMESTAMP())
              <= COALESCE(r.TTL_DAYS, 30)                                   THEN 'FRESH'
         WHEN DATEDIFF('day', e.RETRIEVED_AT, CURRENT_TIMESTAMP()) > 365     THEN 'HARD_STALE'
         ELSE 'STALE'
       END                                                  AS FRESHNESS
  FROM EQUIPMENT_DATA e
  LEFT JOIN SOURCE_REGISTRY r ON r.SOURCE_ID = e.SOURCE_SYSTEM;

-- ── Operations dashboards ───────────────────────────────────────────────
CREATE OR REPLACE VIEW V_AUTOMATION_HEALTH AS
SELECT DATE_TRUNC('hour', STARTED_AT)                         AS HOUR,
       SOURCE,
       COUNT(*)                                               AS RUNS,
       SUM(IFF(STATUS = 'SUCCESS', 1, 0))                     AS SUCCEEDED,
       SUM(IFF(STATUS = 'FAILED', 1, 0))                      AS FAILED,
       ROUND(100 * SUM(IFF(STATUS = 'SUCCESS', 1, 0)) / NULLIF(COUNT(*), 0), 2) AS SUCCESS_PCT,
       MEDIAN(EXECUTION_TIME_MS)                              AS P50_MS,
       APPROX_PERCENTILE(EXECUTION_TIME_MS, 0.95)             AS P95_MS,
       SUM(RETRY_COUNT)                                       AS RETRIES,
       ARRAY_AGG(DISTINCT ERROR_CODE)                         AS ERROR_CODES
  FROM AUTOMATION_RUNS
 GROUP BY 1, 2;

CREATE OR REPLACE VIEW V_DATA_QUALITY AS
SELECT SOURCE_SYSTEM,
       COUNT(*)                                        AS RECORDS,
       AVG(QUALITY_SCORE)                              AS AVG_QUALITY,
       SUM(IFF(EQUIPMENT_MODEL IS NULL, 1, 0))         AS MISSING_MODEL,
       SUM(IFF(BUILD_DATE IS NULL, 1, 0))              AS MISSING_BUILD_DATE,
       SUM(IFF(STATUS = 'QUARANTINED', 1, 0))          AS QUARANTINED,
       AVG(DATEDIFF('day', RETRIEVED_AT, CURRENT_TIMESTAMP())) AS AVG_AGE_DAYS
  FROM EQUIPMENT_DATA
 GROUP BY 1;

-- Full audit reconstruction for any served answer.
CREATE OR REPLACE VIEW V_ANSWER_AUDIT AS
SELECT e.SERIAL_NUMBER, e.SOURCE_SYSTEM, e.EQUIPMENT_MODEL, e.DATA_HASH,
       e.RETRIEVED_AT, e.QUALITY_SCORE, e.FIELD_PROVENANCE,
       r.AUTOMATION_RUN_ID, r.STATUS AS RUN_STATUS, r.STEPS_EXECUTED,
       r.SELECTOR_VERSION, r.ARTIFACT_URI, r.REQUESTED_BY, r.EXECUTION_TIME_MS
  FROM EQUIPMENT_DATA e
  LEFT JOIN AUTOMATION_RUNS r ON r.AUTOMATION_RUN_ID = e.AUTOMATION_RUN_ID;

-- ── Governance ──────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS MAYA_APP;       -- service account: read/write core tables
CREATE ROLE IF NOT EXISTS MAYA_READER;    -- analysts: views only

GRANT USAGE ON DATABASE MAYA_PROD TO ROLE MAYA_APP;
GRANT USAGE ON SCHEMA MAYA_PROD.CORE TO ROLE MAYA_APP;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA MAYA_PROD.CORE TO ROLE MAYA_APP;
GRANT USAGE ON DATABASE MAYA_PROD TO ROLE MAYA_READER;
GRANT USAGE ON SCHEMA MAYA_PROD.CORE TO ROLE MAYA_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA MAYA_PROD.CORE TO ROLE MAYA_READER;

-- Tenant isolation: every query is filtered by the caller's tenant.
CREATE ROW ACCESS POLICY IF NOT EXISTS RAP_TENANT AS (tenant STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ACCOUNTADMIN', 'MAYA_APP') OR tenant = CURRENT_ACCOUNT();
ALTER TABLE EQUIPMENT_DATA ADD ROW ACCESS POLICY RAP_TENANT ON (TENANT_ID);

-- Nightly refresh candidates: what the scheduler should re-pull, oldest first.
CREATE OR REPLACE VIEW V_REFRESH_CANDIDATES AS
SELECT SERIAL_NUMBER, SOURCE_SYSTEM, RETRIEVED_AT, AGE_DAYS, FRESHNESS
  FROM V_EQUIPMENT_CURRENT
 WHERE FRESHNESS IN ('STALE', 'HARD_STALE')
 ORDER BY AGE_DAYS DESC;
