-- Observability and analytics views (Snowflake).

-- Latest run per source per UTC day, plus how many runs happened that day.
CREATE OR REPLACE VIEW V_PIPELINE_DAILY_STATUS AS
SELECT
    TO_DATE(START_TIME)                                         AS RUN_DATE,
    SOURCE,
    RUN_ID,
    COLLECTOR_TYPE,
    STATUS,
    START_TIME,
    END_TIME,
    DATEDIFF('second', START_TIME, END_TIME)                    AS DURATION_SECONDS,
    RECORDS_FOUND,
    RECORDS_VALID,
    RECORDS_LOADED,
    RECORDS_FAILED,
    RECORDS_DUPLICATE,
    RECORDS_INSERTED,
    RECORDS_UPDATED,
    RECORDS_UNCHANGED,
    ERROR_MESSAGE,
    COUNT(*) OVER (PARTITION BY SOURCE, TO_DATE(START_TIME))    AS RUNS_THAT_DAY
FROM PIPELINE_RUNS
QUALIFY ROW_NUMBER() OVER (PARTITION BY SOURCE, TO_DATE(START_TIME) ORDER BY START_TIME DESC) = 1;

-- Current inspections with the runs that first loaded, last changed and last saw them.
CREATE OR REPLACE VIEW V_INSPECTION_LINEAGE AS
SELECT
    i.SOURCE,
    i.INSPECTION_NUMBER,
    i.SERIAL_NUMBER,
    i.STATUS,
    i.INSPECTION_DATE,
    i.FIRST_SEEN_RUN_ID,
    f.START_TIME AS FIRST_SEEN_RUN_START,
    i.LAST_CHANGED_RUN_ID,
    c.START_TIME AS LAST_CHANGED_RUN_START,
    i.LAST_SEEN_RUN_ID,
    l.START_TIME AS LAST_SEEN_RUN_START,
    l.STATUS     AS LAST_SEEN_RUN_STATUS
FROM INSPECTIONS i
LEFT JOIN PIPELINE_RUNS f ON f.RUN_ID = i.FIRST_SEEN_RUN_ID
LEFT JOIN PIPELINE_RUNS c ON c.RUN_ID = i.LAST_CHANGED_RUN_ID
LEFT JOIN PIPELINE_RUNS l ON l.RUN_ID = i.LAST_SEEN_RUN_ID;

-- Validation failures summarised per run and error type.
CREATE OR REPLACE VIEW V_VALIDATION_ERRORS_BY_RUN AS
SELECT
    e.RUN_ID,
    r.START_TIME,
    e.SOURCE,
    e.ERROR_TYPE,
    COUNT(*)                AS FAILURES,
    MIN(e.ERROR_MESSAGE)    AS EXAMPLE_ERROR
FROM VALIDATION_ERRORS e
LEFT JOIN PIPELINE_RUNS r ON r.RUN_ID = e.RUN_ID
GROUP BY e.RUN_ID, r.START_TIME, e.SOURCE, e.ERROR_TYPE;
